language: node_js
node_js:
  - "10"
script:
  - echo 'Build is starting...'
  - echo 'Installing dependencies!'
  - npm install
  - echo 'Build project'
  - npm run build
  - echo 'Deploying now...'
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN